### ISSUE TITLE
Trained weights for mobilenetv2

### ISSUE THREAD

**Issue by gustavz** [balancap/tf-imagenet#1]
Hey @balancap very nice work!
Do you have trained weights for mobilenetv2 on imagenet?
I want to implement a Mask R-CNN with mobilenetv2 as backbine, so the weights could really help me!
Thanks!

**Comment by balancap** [comment]
Thanks!
You can find the trained weights in the `checkpoints` directory. You'll need to install git lfs to download them automatically with git.

**Comment by gustavz** [comment]
@balancap do know how to convert tf ckpt files into keras h5 weight files?
WOuld be great if you cold tell me how to do that!
